name: Publish
on:
  push:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        name: Install Node.js
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
        name: Install dependencies
      - run: yarn test
        name: Run Tests
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}