name: Pull_Request
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          # registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          # scope: "@octocat"
      - name: Install Dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
