name: Pull_Request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-node@v2
        name: Install Node.js
        with:
          node-version: "12.x"
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run Tests
        # env:
